"""
PAC — BehaviourProfile Model

AI-generated criminal behaviour profile aggregated from all linked crimes.
Populated by the Behaviour Intelligence Service (Phase 2).
"""

import uuid
from sqlalchemy import Column, String, Float, DateTime, ForeignKey, func, Text
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship

from app.database import Base


class BehaviourProfile(Base):
    """
    Behavioural fingerprint of a criminal derived from their crime history.

    Captures patterns like preferred operating time, target type, escape method,
    gang size, and operating radius — enabling proactive investigation support.
    """
    __tablename__ = "behaviour_profiles"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    criminal_id = Column(
        UUID(as_uuid=True),
        ForeignKey("criminals.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
        index=True,
    )

    # ── Behavioural patterns ───────────────────────────────
    preferred_crime_types = Column(JSONB, default=list)     # ["chain_snatching", "robbery"]
    preferred_districts = Column(JSONB, default=list)       # ["Bengaluru Urban", "Mysuru"]
    preferred_time_of_day = Column(String(50))              # morning | evening | night
    preferred_target_type = Column(String(100))             # individual | shop | vehicle
    planning_level = Column(String(50))                     # opportunistic | planned | highly_planned
    escape_pattern = Column(String(100))                    # bike | car | foot
    avg_gang_size = Column(Float)
    operating_radius_km = Column(Float)
    crime_frequency_days = Column(Float)                    # avg days between crimes

    # ── Risk assessment ────────────────────────────────────
    risk_score = Column(Float, default=0.0)                 # 0.0 – 1.0
    risk_level = Column(String(20), default="low")          # low | medium | high | critical

    # Natural language summary (generated by LLM in Phase 4)
    profile_summary = Column(Text)

    # Metadata
    generated_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    last_updated = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
    )

    # Relationship
    criminal = relationship("Criminal", back_populates="behaviour_profile")

    def __repr__(self) -> str:
        return f"<BehaviourProfile criminal={self.criminal_id!r} risk={self.risk_level!r}>"
