"""
PAC — CrimeDNA Model

Stores 384-dimensional vector embeddings generated by the ML Engine
using Sentence Transformers (all-MiniLM-L6-v2).

One CrimeDNA record per Crime. Indexed with pgvector IVFFlat for
fast cosine similarity search across all crimes.
"""

import uuid
from sqlalchemy import Column, Text, String, DateTime, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from pgvector.sqlalchemy import Vector

from app.database import Base

# Embedding dimension — must match all-MiniLM-L6-v2 output
EMBEDDING_DIM: int = 384


class CrimeDNA(Base):
    """
    Crime DNA — the behavioural fingerprint of a crime.

    The embedding captures semantic meaning of the MO narrative,
    enabling similarity search beyond keyword matching.

    Example:
        "Entered through rear window using crowbar at midnight"
        "Broke back door glass with iron rod during late night"
    → These are lexically different but semantically identical.
      pgvector cosine similarity detects them as near-identical.
    """
    __tablename__ = "crime_dna"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    crime_id = Column(
        UUID(as_uuid=True),
        ForeignKey("crimes.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
        index=True,
    )

    # 384-dimensional vector embedding
    embedding = Column(Vector(EMBEDDING_DIM), nullable=False)

    # Text used to generate the embedding (for debugging / reindexing)
    mo_text_embedded = Column(Text)

    # Model provenance
    model_name = Column(String(100), default="all-MiniLM-L6-v2", nullable=False)
    model_version = Column(String(50), default="v1.0")

    generated_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationship
    crime = relationship("Crime", back_populates="crime_dna")

    def __repr__(self) -> str:
        return f"<CrimeDNA crime={self.crime_id!r} model={self.model_name!r}>"
