"use client";

import { useState } from "react";
import { useQuery }  from "@tanstack/react-query";
import Link          from "next/link";
import { similarityApi } from "@/lib/api/similarity.api";
import { crimesApi }     from "@/lib/api/crimes.api";
import { LoadingSkeleton } from "@/components/common/LoadingSkeleton";
import { KARNATAKA_DISTRICTS, CRIME_TYPE_LABELS, STALE_TIME } from "@/lib/utils/constants";
import { scoreToPercent } from "@/lib/utils/riskLevel";
import type { CrimeType } from "@/types/api.types";
import { Dna, Search, Filter, Sparkles, FileText, CheckCircle2, ArrowRight } from "lucide-react";
import { format } from "date-fns";

export default function CrimeDnaPage() {
  const [moText, setMoText]         = useState("");
  const [district, setDistrict]     = useState("");
  const [crimeType, setCrimeType]   = useState<CrimeType | "">("");
  const [minScore, setMinScore]     = useState(0.5);
  const [searching, setSearching]   = useState(false);

  // Search query
  const { data: searchResults, refetch: runSearch, isFetching } = useQuery({
    queryKey: ["similarity", "search", { moText, district, crimeType, minScore }],
    queryFn:  () =>
      similarityApi.search({
        mo_text:           moText,
        top_k:             12,
        min_score:         minScore,
        district_filter:   district || undefined,
        crime_type_filter: (crimeType as CrimeType) || undefined,
      }),
    enabled: false,
    staleTime: 0,
  });

  // Recent FIR list to check DNA status
  const { data: recentCrimes, isLoading: crimesLoading } = useQuery({
    queryKey: ["crimes", "dna-list"],
    queryFn:  () => crimesApi.list({ page: 1, page_size: 10 }),
    staleTime: STALE_TIME.crimes,
  });

  const handleSearchSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!moText.trim() || moText.length < 5) return;
    runSearch();
  };

  return (
    <div className="p-6 flex flex-col gap-6 max-w-7xl">
      {/* Header */}
      <div>
        <h1 className="text-[18px] font-bold text-[#e6edf3] flex items-center gap-2">
          <Dna size={22} className="text-[#58a6ff]" />
          Crime DNA & MO Similarity Engine
        </h1>
        <p className="text-[13px] text-[#8b949e] mt-0.5">
          384-dimensional vector embeddings generated by ML Engine for cross-FIR modus operandi pattern matching
        </p>
      </div>

      {/* Free Text MO Vector Search Box */}
      <form onSubmit={handleSearchSubmit} className="pac-card border-[#58a6ff]/40 flex flex-col gap-4">
        <div className="flex items-center justify-between">
          <h2 className="text-[14px] font-semibold text-[#e6edf3] flex items-center gap-2">
            <Sparkles size={16} className="text-[#bc8cff]" />
            Natural Language MO Similarity Search
          </h2>
          <span className="text-[11px] font-mono text-[#58a6ff] bg-[#58a6ff]/10 px-2 py-0.5 rounded border border-[#58a6ff]/30">
            Vector Cosine Similarity
          </span>
        </div>

        <textarea
          rows={3}
          value={moText}
          onChange={(e) => setMoText(e.target.value)}
          placeholder="Describe modus operandi tactics (e.g., two suspect motorcycle night break-in rear window crowbar stolen gold jewelry)..."
          className="w-full bg-[#0d1117] border border-[#30363d] rounded text-[13px] p-3 text-[#e6edf3] placeholder-[#484f58] focus:outline-none focus:border-[#58a6ff]"
        />

        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-3 flex-wrap text-[12px]">
            <select
              value={district}
              onChange={(e) => setDistrict(e.target.value)}
              className="bg-[#0d1117] border border-[#30363d] rounded text-[12px] text-[#e6edf3] px-3 py-1.5 focus:outline-none focus:border-[#58a6ff]"
            >
              <option value="">All Districts</option>
              {KARNATAKA_DISTRICTS.map((d) => (
                <option key={d} value={d}>{d}</option>
              ))}
            </select>

            <select
              value={crimeType}
              onChange={(e) => setCrimeType(e.target.value as CrimeType)}
              className="bg-[#0d1117] border border-[#30363d] rounded text-[12px] text-[#e6edf3] px-3 py-1.5 focus:outline-none focus:border-[#58a6ff]"
            >
              <option value="">All Crime Types</option>
              {Object.entries(CRIME_TYPE_LABELS).map(([k, label]) => (
                <option key={k} value={k}>{label}</option>
              ))}
            </select>

            <div className="flex items-center gap-2 text-[#8b949e]">
              <span>Min Score:</span>
              <input
                type="range"
                min="0.3"
                max="0.9"
                step="0.05"
                value={minScore}
                onChange={(e) => setMinScore(parseFloat(e.target.value))}
                className="w-24 accent-[#58a6ff]"
              />
              <span className="font-mono text-[#e6edf3]">{minScore.toFixed(2)}</span>
            </div>
          </div>

          <button
            type="submit"
            disabled={isFetching || moText.length < 5}
            className="px-5 py-2 bg-[#1f6feb] hover:bg-[#388bfd] disabled:opacity-40 text-white text-[13px] font-semibold rounded flex items-center gap-2 transition-colors shadow-glow-blue"
          >
            <Search size={14} />
            {isFetching ? "Searching Vector Space…" : "Find Similar FIRs"}
          </button>
        </div>
      </form>

      {/* Vector Match Results */}
      {searchResults && (
        <div className="pac-card flex flex-col gap-4 animate-fade-in">
          <h2 className="text-[14px] font-semibold text-[#e6edf3] flex items-center justify-between">
            <span>Ranked Similarity Matches</span>
            <span className="text-[11px] font-mono text-[#8b949e]">
              {searchResults.length} matches found above score {minScore}
            </span>
          </h2>

          {!searchResults.length ? (
            <p className="text-[13px] text-[#8b949e] py-8 text-center">
              No matching FIRs found in the Crime DNA vector space above similarity threshold {minScore}.
            </p>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
              {searchResults.map((m, idx) => (
                <Link
                  key={m.crime_id}
                  href={`/crimes/${m.crime_id}`}
                  className="p-3 rounded bg-[#0d1117] border border-[#30363d] hover:border-[#58a6ff]/40 transition-colors flex flex-col gap-2 group"
                >
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-[11px] font-bold text-[#8b949e]">#{idx + 1}</span>
                    <span className="font-mono text-[12px] font-semibold text-[#58a6ff]">{m.fir_number}</span>
                    <span className="text-[11px] font-mono font-bold text-[#3fb950] bg-[#3fb950]/15 border border-[#3fb950]/30 px-1.5 py-0.5 rounded">
                      {scoreToPercent(m.similarity_score)} match
                    </span>
                  </div>
                  <p className="text-[12px] text-[#c9d1d9] font-medium">
                    {CRIME_TYPE_LABELS[m.crime_type]} · {m.district}
                  </p>
                  {m.mo_text && (
                    <p className="text-[11px] text-[#8b949e] italic line-clamp-2">&quot;{m.mo_text}&quot;</p>
                  )}
                  <div className="flex items-center justify-between text-[10px] text-[#484f58] font-mono pt-1 border-t border-[#21262d]">
                    <span>{format(new Date(m.occurred_at), "dd MMM yyyy")}</span>
                    <span className="text-[#58a6ff] group-hover:underline flex items-center gap-0.5">
                      Inspect <ArrowRight size={10} />
                    </span>
                  </div>
                </Link>
              ))}
            </div>
          )}
        </div>
      )}

      {/* DNA Embedding Pipeline Status List */}
      <div className="pac-card flex flex-col gap-3">
        <h2 className="text-[14px] font-semibold text-[#e6edf3] flex items-center gap-2">
          <CheckCircle2 size={16} className="text-[#3fb950]" />
          Crime DNA Vector Status Index
        </h2>

        {crimesLoading ? (
          <LoadingSkeleton variant="table" />
        ) : (
          <table className="pac-table">
            <thead>
              <tr>
                <th className="text-left">FIR Number</th>
                <th className="text-left">Crime Category</th>
                <th className="text-left">District</th>
                <th className="text-left">Vector Embedding Status</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {recentCrimes?.items.map((c) => (
                <tr key={c.id} onClick={() => window.location.href = `/crimes/${c.id}`}>
                  <td><span className="font-mono text-[#58a6ff] text-[12px]">{c.fir_number}</span></td>
                  <td className="text-[12px] text-[#c9d1d9]">{CRIME_TYPE_LABELS[c.crime_type]}</td>
                  <td className="text-[12px] text-[#8b949e]">{c.district}</td>
                  <td>
                    <span className="text-[11px] font-mono px-2 py-0.5 rounded bg-[#3fb950]/15 text-[#3fb950] border border-[#3fb950]/30 inline-flex items-center gap-1">
                      <CheckCircle2 size={11} /> 384-dim Embedded
                    </span>
                  </td>
                  <td>
                    <Link href={`/crimes/${c.id}`} className="text-[12px] text-[#58a6ff] hover:underline">
                      View DNA →
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
